### ISSUE TITLE
NotImplementedError while running the testing code in model.py

### ISSUE THREAD

**Issue by JizeCao** [zihangdai/mos#7]
I try to run the script model.py. But a NotImplementedError occurs.
`Traceback (most recent call last):
  File "/Users/TONY/Downloads/mos-master/model.py", line 131, in <module>
    model(input, hidden)
  File "/Users/TONY/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
param size: 4426
    result = self.forward(*input, **kwargs)
  File "/Users/TONY/Downloads/mos-master/model.py", line 71, in forward
    emb = embedded_dropout(self.encoder, input, dropout=self.dropoute if self.training else 0)
  File "/Users/TONY/Downloads/mos-master/embed_regularize.py", line 19, in embedded_dropout
    X = embed._backend.Embedding.apply(words, masked_embed_weight,
  File "/Users/TONY/anaconda/lib/python3.6/site-packages/torch/nn/backends/backend.py", line 10, in __getattr__
    raise NotImplementedError
NotImplementedError
`

**Comment by kimiyoung** [comment]
This codebase only supports pytorch 0.2.0 at this point. Also using this version makes it possible to exactly reproduce the results in our paper.

**Comment by JizeCao** [comment]
Thanks!
